[project]
name = "py-pyside"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Renato Cruz", email = "natorsc@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.11.2",
    "qtbridge>=0.2.0",
]

[project.scripts]
py-pyside = "py_pyside:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
