[project]
name = "py-pyside"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Renato Cruz", email = "natorsc@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.11.2",
    "qtbridge>=0.2.0",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors.
    "F",   # pyflakes.
    "I",   # isort (organização de imports).
]

[tool.ruff.lint.isort]
combine-as-imports = true
